### ISSUE TITLE
-webkit- prefix is not being added for transform properties

### ISSUE THREAD

**Issue by tomoguisuru** [kimroen/ember-cli-autoprefixer#12]
When using the default options, ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1'], the -webkit- prefix is not being applied to css transform properties for Safari which according to CanIUse, http://caniuse.com/#feat=transforms2d, are still required

**Comment by kimroen** [comment]
Problems with Autoprefixer itself should probably be directed at them directly: https://github.com/postcss/autoprefixer

If this problem is because of something I'm doing here though, please let me know!
