### ISSUE TITLE
Deprecation of Autoprefixer's process() method

### ISSUE THREAD

**Issue by buschtoens** [kimroen/ember-cli-autoprefixer#13]
Since very recently installing `ember-cli-autoprefixer` results in this deprecation warning during a build:
```
jan@ubuntu:~/code/citb$ ember serve
version: 0.2.5
Livereload server on port 35729
Serving on http://localhost:4200/
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead
Autoprefixer's process() method is deprecated and will removed in next major release. Use postcss([autoprefixer]).process() instead

Build successful - 7662ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Concat: Vendor                                | 4425ms
Babel                                         | 744ms
Babel                                         | 444ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Concat: Vendor (1)                            | 4425ms
Babel (4)                                     | 1458ms (364 ms)
```

**Comment by buschtoens** [comment]
It appears like they've changed the whole build pipeline an Autoprefixer is now a plugin of [PostCSS](https://github.com/postcss/postcss).

**Comment by oskarrough** [comment]
Yea, take a look at https://github.com/jeffjewiss/ember-cli-postcss

**Comment by ilkkao** [comment]
I couldn't find a simple way to get `ember-cli-postcss` and `ember-cli-less` to work together. `ember-cli-autoprefixer` works fine with `ember-cli-less` so for the time being I'll keep using it even the warning is a little annoying.

**Comment by kimroen** [comment]
Thanks for reporting this, and sorry that I haven't been more responsive. `broccoli-autoprefixer` was just updated to use postcss, so I released a new version now that depends on this new version. This should make the annoying warning go away :)

Thanks to @salzhrani for reporting it over there: https://github.com/sindresorhus/broccoli-autoprefixer/issues/9

Regarding ember-cli-postcss: I think that is a great thing to have, but I also think there is value in having a dedicated addon just for autoprefixer alone to make it super simple to set that up if that's all you need. That is the case for a lot of people.

**Comment by salzhrani** [comment]
Woot!!!
