### ISSUE TITLE
not working (for me) with ember-cli 1.13.8

### ISSUE THREAD

**Issue by benkonrath** [kimroen/ember-cli-autoprefixer#23]
I'm not able to get the autoprefixer to work with ember-cli 1.13.8. I'm not sure what's going on but I thought I'd ask to see if there's something that I'm missing. I appreciate help or pointers you can give me. 

I couldn't get the autoprefixer to work in my full app so I tried in a new test app which is also not working. Here's how I set it up.

```sh
$ ember --version
version: 1.13.8
node: 0.12.7
npm: 2.13.4
os: linux x64
$ mkdir test-app
$ cd test-app
$ ember init
$ ember install ember-cli-autoprefixer
```

Add autoprefixer config to ember-cli-build.js
```js
var app = new EmberApp(defaults, {
  autoprefixer: {
    browsers: ['> 1%', 'last 2 versions', 'Firefox ESR', 'Opera 12.1', 'Explorer >= 8'],
    cascade: false
  }
});
```

Add test css to app/styles/app.css:
```css
.foo2 {
  opacity: 0.5;
  border-radius: 4px;
}
```
Run `ember serve` and check css output:

```
$ cat dist/assets/test-app.css
.foo {
  opacity: 0.5;
  border-radius: 4px;
}
```

I would expect the output to have the vendor prefixes. Am I missing something obvious? Do you have any suggestions on how I can debug this issue? Thanks.

**Comment by kimroen** [comment]
Hi! I don't think any of the styles in your CSS needs to be prefixed - [`border-radius` is supported in all the browsers you asked for with no prefix](http://caniuse.com/#feat=border-radius).

Would you mind testing with some other styles, like `user-select: none;`, just to be sure?

**Comment by benkonrath** [comment]
It is in fact working with `user-select: none;` so there's no problem. I expected to get `-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";` for the `opacity: 0.5;` but it looks like I'll have to use https://github.com/cssdream/cssgrace or https://github.com/iamvdo/postcss-opacity with ember-cli-postcss if I want this. Thanks for the help and for sharing this useful ember-cli app.

**Comment by kimroen** [comment]
Happy you got it worked out :)
