### ISSUE TITLE
Can't find options when nested in an addon

### ISSUE THREAD

**Issue by mattgrannary** [kimroen/ember-cli-autoprefixer#28]
I tried installing this addon in another addon so I could provide vendored styles but the include method failed because it was trying to find the options hash on the app and the app doesn't include this when nested.

I've created a quick MR #27 to allow this addon to switch to the app's app property to get the options.

**Comment by kimroen** [comment]
Thanks for your fix - this has been released as `v0.6.0`.

**Comment by mattgrannary** [comment]
Sweet!
