### ISSUE TITLE
Should use browserlist config from package.json

### ISSUE THREAD

**Issue by amk221** [kimroen/ember-cli-autoprefixer#31]
...and/or the browserlist dotfile. If no config is set in `ember-cli-build.js`

**Comment by amk221** [comment]
It seems that this is was not working for me due to `browserslist 1.4.0` being installed instead of `1.7.1`

**Comment by NindroidX** [comment]
I know it's an old issue, but how did you get this to work? It doesn't seem to use the browsers I specify in the .browserslistrc file (and `npx browserslist` / `npx autoprefixer --info` do show the correct browsers).
