### ISSUE TITLE
Make use of the new `this.project.targets` feature

### ISSUE THREAD

**Issue by cibernox** [kimroen/ember-cli-autoprefixer#32]
First, some context: https://github.com/ember-cli/rfcs/blob/master/active/0095-standardise-targets.md

The idea behind that is that now Ember apps have a single unique standarized source of truth for defining the browsers in which the app is intended to be executed.

This means that the some tools can be smart and change how they work based on that information.

- `ember-cli-babel` 6.0.0 already transpiles only the features that are not natively supported on your targets. By example, if your app runs on chrome only, it won't transpile `async/await`.
- `ember-maybe-import-regenerator` will conditionally import the regenerator runtime only if needed: https://github.com/machty/ember-maybe-import-regenerator/pull/4

This addon could do the same to decide wether or not a css property has to be prefixed. 
I won't have time to implement the feature myself in the next weeks, but I will be happy to give some guidance to someone who has.

**Comment by kimroen** [comment]
Sorry, I just saw this. That seems really cool, thank you for the information!
