### ISSUE TITLE
Up for adoption?

### ISSUE THREAD

**Issue by jrjohnson** [kimroen/ember-cli-autoprefixer#44]
@kimroen I'm wondering if you would be interested in moving this addon to https://github.com/adopted-ember-addons and opening up for some community maintenance?

Or if you would prefer it remain here I would be happy to help with some PR maintenance.

**Comment by Windvis** [comment]
I think deprecating this repo and using autoprefixer with ember-cli-postcss might be a better option, no?

**Comment by snewcomer** [comment]
1.0.0 published!
