### ISSUE TITLE
missin semi-colon error when building apps with v1.0.0

### ISSUE THREAD

**Issue by fran-worley** [kimroen/ember-cli-autoprefixer#49]
I've had this in 3 apps. When updating from <1 to v1 I get a build error:

```
Build Error (broccoli-persistent-filter:Filter) in assets/dummy.css.map:1:788

/Projects/ember-light-table/assets/dummy.css.map:1:788: Missed semicolon> 
```

You can recreate this in the dummy app for ember-light-table by bumping the autoprefixer addon.
Any ideas?

**Comment by snewcomer** [comment]
Oh no!  Did you create a PR @fran-worley?  I had some problems but had to cleanup the world (rm -rf tmp dist node_modules and maybe other stuff) before it worked.

**Comment by fran-worley** [comment]
Thanks @snewcomer I've tried cleaning up and I still get the same issue. I've not raised a PR as if I'm honest I've no idea where to start! I guess it's possible that the issue is not here but in autoprefixer itself?

I had hopped this was a common issue! 😥

**Comment by dknutsen** [comment]
Just tried bumping to v1 and I'm seeing same thing

**Comment by artemgurzhii** [comment]
same for me, `0.8.1` works fine, bumping to the `1.0.0` fails

**Comment by miguelcobain** [comment]
Same thing happens here.

**Comment by snewcomer** [comment]
Has anybody gotten this to work?  I had issues at the start, but if I recall, it was solved through cleanup.  What Node are you on?

**Comment by nag5000** [comment]
It seems https://github.com/kimroen/ember-cli-autoprefixer#note-on-using-with-ember-cli-sass fixes this error for me (I use ember-cli-sass).

**Comment by snewcomer** [comment]
For those that are curious, this is an example config for us after upgrading (was part of my commit to upgrade to 1.0.0)!  Thank you @nag5000 for pointing this out!

```
    autoprefixer: {
        enabled: true,
        cascade: true,
        sourcemap: !envIsProduction
    },
    sassOptions: {
      sourceMapEmbed: !envIsProduction,
      implementation: sass,
      cacheInclude: [/\.(css|scss)$/]
    },

```

Let me know if this (or some other form) doesn't work for somebody!
