### ISSUE TITLE
sourcemaps

### ISSUE THREAD

**Issue by salzhrani** [kimroen/ember-cli-autoprefixer#9]
`ember-cli-sass` provides the sourcemaps inline, but once they go through `ember-cli-autoprefixer` they are not there anymore.

**Comment by kimroen** [comment]
Could you check if setting this fixes the issue?

https://github.com/sindresorhus/broccoli-autoprefixer#sourcemap

How to set:

https://github.com/kimroen/ember-cli-autoprefixer#options

**Comment by salzhrani** [comment]
My Brocfile
```
var app = new EmberApp({
    autoprefixer: {
        sourcemap: true
    }
});
```

**Comment by kimroen** [comment]
That's interesting. As you can see, I don't really do anything with the options, I just pass everything except `enabled` through to `broccoli-autoprefixer`:

https://github.com/kimroen/ember-cli-autoprefixer/blob/75d8e9d7a643abc9d21d3b554a8c4c73435e2007/index.js#L19

I don't have time to dig in to it more right now, but I might this weekend.

**Comment by kimroen** [comment]
I've been looking at this for a little while today, and was initially pleased to find that these combinations both produce a css-file with an inline sourcemap:

- broccoli-sass + ember-cli-autoprefixer
- ember-cli-sass + ember-cli-autoprefixer

Unfortunately, when I looked more, I realized that I hadn't managed to set up ember-cli-sass to output inline sourcemaps, as there was none when I removed ember-cli-autoprefixer from the mix.

I haven't been able to make ember-cli-sass output a css-file with an embedded sourcemap so far. Can you please verify that you have managed to make this work, and maybe share your setup? (Just so I'm not debugging something that doesn't work).

**Comment by salzhrani** [comment]
For ember-cli-sass to show you need to add this to `environment.js`
```
sassOptions: {
        sourceComments: true
    }
``` 
which was my problem too.

Thank you for taking the time to look at this.

**Comment by kimroen** [comment]
Happy you figured it out :)
